
application: flask-start # cf. id de l'application acquise sur appengine.google.com
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Pensez à apprendre le REGEX!
handlers:


# url vraie si l'url demandée par l'utilisateur commence par <appid>.appspot.com/admin/
- url: /admin/.*
  # Si la requête est de la forme définit plus haut, traiter cette dernière avec le fichier main.py
  script: main.app
  # Accès limité aux administrateurs de l'application
  login: admin

# url vraie si vide ou ne contient pas de point  
- url: /[^.]*
  # Si la requête est de la forme définit plus haut, traiter cette dernière avec le fichier main.py
  script: main.app

# sinon chercher dans le dossier static selon l'url spécifiée
# Les urls contentant .css, .js, .html, ... sont captées !
- url: /
  static_dir: static


libraries:
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?.*\.py[co]$
- ^\.git$